VALID_LM_STUDIO_PARAMS = [
    "model",
    "messages",
    "max_tokens",
    "temperature",
    "top_p",
    "top_k",
    "stream",
    "price",
    "stop",
    "presence_penalty",
    "frequency_penalty",
    "logit_bias",
    "repeat_penalty",
    "seed",
    "promt",
]
